[workspace]

members = ["hello", "rest-post", "lib"]

[workspace.dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
serde = "1.0.175"
serde_json = "1.0.103"
aws-sdk-dynamodb = "0.28.0"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+0_28"] }
